# Generated by Django 5.1.3 on 2024-11-29 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_fooditem_image_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='disliked_food_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_food_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
