# Generated by Django 5.1.3 on 2024-11-30 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_fooditem_dislikes_fooditem_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
